# fly.toml app configuration file generated for billowing-tree-8403 on 2023-05-22T16:26:41+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "billowing-tree-8403"
primary_region = "lhr"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
